added generators for random data
HackerDom/Gornilo pull request #11
Opened 2022-08-16 21:57 UTC by keltecc

Added helpful functions for random data generation:

```python
> import gornilo
> gornilo.random_username()
'alarmed_east_2wjxb0'
> gornilo.random_password()
'oVzfrSBgbySw0hIC'
> gornilo.random_xkcd_password()
'LOVE_LIP_GLAD_SPRING_SERVICE_EXPERT'
> gornilo.random_text()
'Pension optimal you silent setting nutty. Glass frank smell truck close known. Worried humble zigzag article anybody usual. Low annual airline male cross anxious.'
```

2022-08-20 08:52 UTC, 1MiKHalyCH1 requested changes

2022-08-20 17:06 UTC, keltecc commented
This PR fixes issue #13

2022-08-20 17:12 UTC, keltecc commented on gornilo/__init__.py
> +from gornilo.generators import (
Я бы не стал оставлять в подпакете, потому что предполагаю, что это одна из основных и часто используемых фич. При этом остаётся возможность и явно импортнуть `gornilo.generators`, если нужно

2023-11-01 08:18 UTC, rx00 approved these changes

2023-11-01 08:23 UTC, merged